/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppQuizResultRouteImport } from './routes/app.quiz-result'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppMockTestRouteImport } from './routes/app.mock-test'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppInviteRouteImport } from './routes/app.invite'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppHazardRouteImport } from './routes/app.hazard'
import { Route as AppDriveSummaryRouteImport } from './routes/app.drive-summary'
import { Route as AppDriveActiveRouteImport } from './routes/app.drive-active'
import { Route as AppDriveRouteImport } from './routes/app.drive'
import { Route as AppCommunityRouteImport } from './routes/app.community'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizResultRoute = AppQuizResultRouteImport.update({
  id: '/quiz-result',
  path: '/quiz-result',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppMockTestRoute = AppMockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHazardRoute = AppHazardRouteImport.update({
  id: '/hazard',
  path: '/hazard',
  getParentRoute: () => AppRoute,
} as any)
const AppDriveSummaryRoute = AppDriveSummaryRouteImport.update({
  id: '/drive-summary',
  path: '/drive-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppDriveActiveRoute = AppDriveActiveRouteImport.update({
  id: '/drive-active',
  path: '/drive-active',
  getParentRoute: () => AppRoute,
} as any)
const AppDriveRoute = AppDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/drive': typeof AppDriveRoute
  '/app/drive-active': typeof AppDriveActiveRoute
  '/app/drive-summary': typeof AppDriveSummaryRoute
  '/app/hazard': typeof AppHazardRoute
  '/app/help': typeof AppHelpRoute
  '/app/home': typeof AppHomeRoute
  '/app/invite': typeof AppInviteRoute
  '/app/learn': typeof AppLearnRoute
  '/app/mock-test': typeof AppMockTestRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/quiz-result': typeof AppQuizResultRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/drive': typeof AppDriveRoute
  '/app/drive-active': typeof AppDriveActiveRoute
  '/app/drive-summary': typeof AppDriveSummaryRoute
  '/app/hazard': typeof AppHazardRoute
  '/app/help': typeof AppHelpRoute
  '/app/home': typeof AppHomeRoute
  '/app/invite': typeof AppInviteRoute
  '/app/learn': typeof AppLearnRoute
  '/app/mock-test': typeof AppMockTestRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/quiz-result': typeof AppQuizResultRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/drive': typeof AppDriveRoute
  '/app/drive-active': typeof AppDriveActiveRoute
  '/app/drive-summary': typeof AppDriveSummaryRoute
  '/app/hazard': typeof AppHazardRoute
  '/app/help': typeof AppHelpRoute
  '/app/home': typeof AppHomeRoute
  '/app/invite': typeof AppInviteRoute
  '/app/learn': typeof AppLearnRoute
  '/app/mock-test': typeof AppMockTestRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/quiz-result': typeof AppQuizResultRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/community'
    | '/app/drive'
    | '/app/drive-active'
    | '/app/drive-summary'
    | '/app/hazard'
    | '/app/help'
    | '/app/home'
    | '/app/invite'
    | '/app/learn'
    | '/app/mock-test'
    | '/app/more'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/progress'
    | '/app/quiz'
    | '/app/quiz-result'
    | '/app/schedule'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/community'
    | '/app/drive'
    | '/app/drive-active'
    | '/app/drive-summary'
    | '/app/hazard'
    | '/app/help'
    | '/app/home'
    | '/app/invite'
    | '/app/learn'
    | '/app/mock-test'
    | '/app/more'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/progress'
    | '/app/quiz'
    | '/app/quiz-result'
    | '/app/schedule'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/community'
    | '/app/drive'
    | '/app/drive-active'
    | '/app/drive-summary'
    | '/app/hazard'
    | '/app/help'
    | '/app/home'
    | '/app/invite'
    | '/app/learn'
    | '/app/mock-test'
    | '/app/more'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/progress'
    | '/app/quiz'
    | '/app/quiz-result'
    | '/app/schedule'
    | '/app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz-result': {
      id: '/app/quiz-result'
      path: '/quiz-result'
      fullPath: '/app/quiz-result'
      preLoaderRoute: typeof AppQuizResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mock-test': {
      id: '/app/mock-test'
      path: '/mock-test'
      fullPath: '/app/mock-test'
      preLoaderRoute: typeof AppMockTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invite': {
      id: '/app/invite'
      path: '/invite'
      fullPath: '/app/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hazard': {
      id: '/app/hazard'
      path: '/hazard'
      fullPath: '/app/hazard'
      preLoaderRoute: typeof AppHazardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drive-summary': {
      id: '/app/drive-summary'
      path: '/drive-summary'
      fullPath: '/app/drive-summary'
      preLoaderRoute: typeof AppDriveSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drive-active': {
      id: '/app/drive-active'
      path: '/drive-active'
      fullPath: '/app/drive-active'
      preLoaderRoute: typeof AppDriveActiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drive': {
      id: '/app/drive'
      path: '/drive'
      fullPath: '/app/drive'
      preLoaderRoute: typeof AppDriveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppDriveRoute: typeof AppDriveRoute
  AppDriveActiveRoute: typeof AppDriveActiveRoute
  AppDriveSummaryRoute: typeof AppDriveSummaryRoute
  AppHazardRoute: typeof AppHazardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInviteRoute: typeof AppInviteRoute
  AppLearnRoute: typeof AppLearnRoute
  AppMockTestRoute: typeof AppMockTestRoute
  AppMoreRoute: typeof AppMoreRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuizRoute: typeof AppQuizRoute
  AppQuizResultRoute: typeof AppQuizResultRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppDriveRoute: AppDriveRoute,
  AppDriveActiveRoute: AppDriveActiveRoute,
  AppDriveSummaryRoute: AppDriveSummaryRoute,
  AppHazardRoute: AppHazardRoute,
  AppHelpRoute: AppHelpRoute,
  AppHomeRoute: AppHomeRoute,
  AppInviteRoute: AppInviteRoute,
  AppLearnRoute: AppLearnRoute,
  AppMockTestRoute: AppMockTestRoute,
  AppMoreRoute: AppMoreRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuizRoute: AppQuizRoute,
  AppQuizResultRoute: AppQuizResultRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
